version: "3.4"
services:
  task_admin_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_admin_app
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: bash -c "npm start"
