version: "3.4"
services:
  task_admin_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_admin_api
    expose:
      - '3666'
    ports:
      - '3666:3666'
    command: bash -c "/usr/wait-for-it.sh --timeout=0 mongo:27017 && node dist/server.js"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
